package com.example.volunteeryapp.Navigations
const val ROUTE_HOME = "home"
const val ROUTE_JOIN ="join"
const val ROUTE_REGISTER = "register"
const val ROUTE_REGISTERORG ="registerOrg"
const val ROUTE_LOGIN= "login"
const val ROUTE_DASHBOARD = "dashboard"
const val ROUTE_DASHBOARDORG ="dashboardOrg"
const val ROUTE_WELCOME = "welcome"
const val ROUTE_SEARCH ="search"
const val ROUTE_SETTINGS ="settings"
const val ROUTE_CALENDER ="calender"
const val ROUTE_OPPORTUNITIES ="opportunities"
const val ROUTE_ADD_OPPORTUNITY = "addOpportunity"
const val ROUTE_VIEW_OPPORTUNITY = "viewOpportunity"
const val ROUTE_UPDATE_OPPORTUNITY ="updateOpportunity"
const val ROUTE_VIEW = "view"